### ISSUE TITLE
RAM problem

### ISSUE THREAD

**Issue by milen-prg** [PIBSAS/ESP32-S3-WROOM-1-N16R8#1]
I installed your release ready MicroPython version on my ESP32 S3 N16R8.

```
MicroPython v1.23.0-preview.184.gbf68bb95f on 2024-03-07; ESP32S3 module (spiram) with ESP32S3
Type "help()" for more information.
 
But:

>>> import gc
>>> gc.collect()
>>> gc.mem_free()

267120
```

Only about 200kB. (from embedded in the bare chip 512k). 

And really after creating list with less 50000 integers (x4B = about 200k), it gives message:
MemoryError: memory allocation failed, allocating .... bytes
And can't allocate more.
 
Is it possible to use the enormous 8MB PSRAM with MicroPython on my dev kit?
Thank, you in advance!

**Comment by milen-prg** [comment]
This see 8MB PSRAM, excellent! But ONLY 8MB Flash! The Flash is 16MB and the old version given properly gc.mem_free(). Now:

`MicroPython df41913 on 2024-05-24; Generic ESP32S3 module with Octal-SPIRAM with ESP32S3

Type "help()" for more information.

>>> import os
>>> s = os.statvfs('//')
>>> s
(4096, 4096, 1536, 1533, 1533, 0, 0, 0, 0, 255)
>>> '{0} MB'.format((s[0]*s[3])/1048576)
'5.988281 MB'
>>> import esp
>>> esp.flash_size()
8388608
>>> import gc
>>> gc.mem_free()
8299616`

Thank, you for fast support! If correct also the flash size and all other works, this will be the only working version of Python for this kits, because I tried also Circuit python special version, which do not work at all.

**Comment by PIBSAS** [comment]
Thanks for advice, i share this only, i dont have enough knowledge to resolve quickly
```bash
MicroPython v1.22.2-dirty on 2024-03-08; Generic ESP32S3 module with ESP32S3

Type "help()" for more information.

>>> import os
>>> s = os.statvfs('//')
>>> s
(4096, 4096, 3584, 3575, 3575, 0, 0, 0, 0, 255)
>>> import esp
>>> esp.flash_size()
16777216
>>> import gc
>>> gc.mem_free()
8289600
>>> 
```

![Captura de pantalla 2024-05-25 130643](https://github.com/PIBSAS/ESP32-S3-WROOM-1-N16R8/assets/38385411/3c7dd233-6ead-42f2-a89f-e439d750a7af)

Obviously, this is the old and first compile sucessfully did that day when create this repo with  the steps for reproduce. I will make a new compile today and see the error you found,and search how to  fix it. Thanks again

**Comment by PIBSAS** [comment]
Yes, all compile, have 16Mb but only 231kb PSRAM, i will look for solution. Thanks!
![Captura de pantalla 2024-05-25 143302](https://github.com/PIBSAS/ESP32-S3-WROOM-1-N16R8/assets/38385411/b2ce5bd0-6192-4a90-8b8c-d3c22e3ad9e3)

**Comment by PIBSAS** [comment]
Fixed, i've applied the changed made by Mythologyli to get back, thanks to your question @milen-prg. Added instructions to use ESP-IDF v5.2.

```bash
MicroPython v1.23.0-preview.392.gdf4191378 on 2024-05-25; Generic ESP32S3 module with Octal-SPIRAM with ESP32S3

Type "help()" for more information.

>>> import os
>>> s = os.statvfs('//')
>>> s
(4096, 4096, 3584, 3581, 3581, 0, 0, 0, 0, 255)
>>> import esp
>>> esp.flash_size()
16777216
>>> import gc
>>> gc.mem_free()
8289024
>>> 
```

![Captura de pantalla 2024-05-25 143302](https://github.com/PIBSAS/ESP32-S3-WROOM-1-N16R8/assets/38385411/fa0fd6ff-9ddc-4a88-896a-b88f7eb7e25c)
