### ISSUE TITLE
Can the smartconfig feature be added

### ISSUE THREAD

**Issue by bequt** [PIBSAS/ESP32-S3-WROOM-1-N16R8#2]
Can the smartconfig feature be added

https://gitee.com/walkline/micropython-smartconfig-cmodule

**Comment by PIBSAS** [comment]
See in release:
![Captura de pantalla 2024-09-17 090731](https://github.com/user-attachments/assets/74e42b38-2c80-481d-9006-1c180060c2a4)
cheers!

**Comment by PIBSAS** [comment]
Works!, I added the example use here in the repo, is in [smartconfig_example](smartconfig_example) folder: 
![Captura de pantalla 2024-09-17 100217](https://github.com/user-attachments/assets/c54cd7b4-2843-4947-9f89-3a4ab315e681)

**Comment by bequt** [comment]
Thank you, you've worked hard.

**Comment by PIBSAS** [comment]
Close the issue when you really test that works for you, have a good day!

**Comment by walklinewang** [comment]
@PIBSAS thanks for your help, by the way, if possible please head over to [this pr](https://github.com/micropython/micropython/pull/13658) for comments and suggestions, I wish the officials would have merged this pr sooner so it would have saved some extra steps.

**Comment by PIBSAS** [comment]
One question, well 2, please head over to this pr for comments and suggestions. I did right? maybe lost in the translation, second, you will update to newest IDF?. and third Thanks for the module, hope that micropython added, is a really needed feauture, by mistake i flashed to T-Display S3 and works(i confuse the repo hehe). So it works in ESP32-S3 obviously and in T-Display S3(but without stt7789 driver).

**Comment by walklinewang** [comment]
> please head over to this pr for comments and suggestions. I did right?

Yes, thanks for your reply in that pr.


> second, you will update to newest IDF?

I don't know which version of IDF you're using now. I'm using v5.1.2 which is, mainly for compatibility with the esp32 firmware, there are some issues compiling with v5.2 (2 months ago), and theoretically SmartConfig will work with more IDF versions.

> So it works in ESP32-S3 obviously and in T-Display S3(but without stt7789 driver).

To compile more than one user c modules into firmware, you have to write down a new cmake file, looks like [this](https://github.com/micropython/micropython/blob/master/examples/usercmodule/micropython.cmake), used to  contain all modules you needed, and point the USER_C_MODULES parameter to its path.

**Comment by PIBSAS** [comment]
I'm using IDF v5.2.2 see the [buil.yaml](.github/workflows/build.yaml)
